spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projetsprings2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

jwt:
    secret: jwtsecret
bcrypt:
    salt: 10

